version: "3.5"

services:
  php_fpm:
      build: .
      container_name: tf_php_fpm
      working_dir: /usr/share/nginx/tf
      networks:
        - tf
      volumes:
          - ./:/usr/share/nginx/tf

  nginx:
      image: nginx:1.15
      container_name: tf_nginx
      working_dir: /usr/share/nginx/tf
      networks:
        - tf
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/tf
          - ./docker/nginx/conf.d:/etc/nginx/conf.d

  mysql:
      image: mysql:5.7
      container_name: tf_mysql
      networks:
        - tf
      environment:
        - MYSQL_DATABASE=tf
        - MYSQL_ROOT_PASSWORD=borjas
        - MYSQL_USER=tf_user
        - MYSQL_PASSWORD=borjas

networks:
  tf:
    driver: bridge